# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dinosaurscode
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dinosaurscode.xyz" # the base hostname & protocol for your site
enforce_url: "dinosaurscode.xyz"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown 
highlighter: rouge 

#markdown: kramdown

#kramdown:
#  input: GFM
#  hard_wrap: false
#  syntax_highlighter: rogue

webrick:
  headers:
    Dino: Says welcome to my website ;)

exclude:
  - package.json
  - node_modules
  - gulpfile.js

environment: production 
#production
